<a href="https://colab.research.google.com/github/jisunclaralee/blank-app/blob/main/2_%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 넘파이 배열 연산
## 1. 연산함수

In [2]:
import numpy as np
test_array = np.arange(1,11)
test_array.sum()

np.int64(55)

In [3]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [5]:
test_array.sum(axis=1)

array([10, 26, 42])

In [6]:
test_array = np.arange(1,13).reshape(3,4)
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [7]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [8]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [9]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [10]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [12]:
test_array.std()
#전체 값에 대한 표준편차 계산

np.float64(3.452052529534663)

In [13]:
test_array.std(axis=0)
#axis=0 축을 기준으로 표준편차 계산

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [14]:
np.sqrt(test_array)
# 각 요소에 제곱근 연산 수

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

## 2. 연결함수

In [15]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack((v1,v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [18]:
v1 = v1.reshape(-1, 1)
v2 = v2.reshape(-1, 1)
v1

array([[1],
       [2],
       [3]])

In [19]:
v2

array([[4],
       [5],
       [6]])

In [20]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4,5,6]])
np.concatenate((v1,v2),axis=0)
#concatenate함수 : 축을 고려해서 두개 배열 결합

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
v1 = np.array([1,2,3,4]).reshape(2,2)
v2 = np.array([[5,6]]).T
v1

array([[1, 2],
       [3, 4]])

In [23]:
v2

array([[5],
       [6]])

In [24]:
np.concatenate((v1,v2),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

## 3. 사칙연산함수

In [71]:
x = np.arange(1, 7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [73]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [74]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [75]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [27]:
#dot합수
x_1 = np.arange(1,7).reshape(2,3)
x_2 = np.arange(1,7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [37]:
#브로드캐스팅 연산
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
x+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [32]:
x-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [33]:
x//3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]])

In [35]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [38]:
x = np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
v = np.arange(10,40,10)
v

array([10, 20, 30])

In [40]:
v = np.arange(10, 40, 10)
v

array([10, 20, 30])

In [44]:
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

#비교 연산과 데이터 추출
##1.1브로드캐스팅형 비교 연산

In [48]:
x = np.array([4,3,2,6,8,5])
x>3

array([ True, False, False,  True,  True,  True])

##1.2 요소별 비교 연산

In [49]:
x=np.array([1,3,0])
y=np.array([2,2,7])

x>y

array([False,  True, False])

## 2. 비교 연산 함수
### 1. all 과 any

In [50]:

x = np.array([4,6,7,3,2])
x>3

array([ True,  True,  True, False, False])

In [51]:
(x<3).all()

np.False_

In [52]:
(x>3).any()

np.True_

In [53]:
(x<10).any()

np.True_

In [54]:
(x>10).any()

np.False_

## 2.2인덱스 반환 함수 -  where 함수

In [55]:

x = np.array([4,6,7,3,2])
x>5

array([False,  True,  True, False, False])

In [56]:
np.where(x>5)

(array([1, 2]),)

In [57]:
x = np.array([4,6,7,3,2])
np.where(x>5, 10, 20)

array([20, 10, 10, 20, 20])

## 2.3 정렬된 값의 인덱스를 반환해주는 함수 argsort / argmax / argmin

In [59]:
x = np.array([4,6,7,3,2,])
np.argsort(x)

array([4, 3, 0, 1, 2])

In [60]:
np.argmax(x)

np.int64(2)

In [61]:
np.argmin(x)

np.int64(4)

#3. 인덱스를 활용한 데이터 추출
## 1. 불린인덱스

In [62]:
x = np.array([4,6,7,3,2])
x>3

array([ True,  True,  True, False, False])

In [64]:
cond = x > 3
x[cond]

array([4, 6, 7])

In [65]:
x.shape

(5,)

In [66]:
cond.shape

(5,)

## 3.2 팬시 인덱스

In [67]:
x = np.array([4,6,7,3,2])
cond = np.array([1,2,0,2,2,2,],int)
x[cond]

array([6, 7, 4, 7, 7, 7])

In [68]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [70]:
x = np.array([[1,4],[9,16]],int)
a = np.array([0,1,1,1,0,0],int)
b= np.array([0,0,0,1,1,1],int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])